# -*- coding: utf-8 -*-
"""s1 합치는중의 사본의 사본--이걸로하세욤

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13oTxxPzC_rEARF9o4nogYesj-pCVBKYm
"""


from google import genai
from google.colab import userdata
from IPython.display import Markdown

API_KEY = userdata.get('GEMINI_API_KEY')
client = genai.Client(api_key=API_KEY)

response = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents="Explain how quantum computing works to a five-year-old."
)

display(Markdown(response.text))

import os
import json
import re
import pandas as pd
import numpy as np
# import from google for Gemini API
import google.generativeai as genai
from google.colab import userdata

# Google Gemini API 클라이언트 초기화
GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')
genai.configure(api_key=GEMINI_API_KEY)
gemini_model = genai.GenerativeModel('gemini-3-flash-preview')

# [글로벌 상수 및 14차원 카테고리 정의]
LABELS = [
    "육류", "가공육", "어패류", "가금류알", "유제품",
    "견과류", "땅콩", "갑각류", "생선", "밀", "달걀", "유제품알러지", "대두", "참깨"
]
ALLERGY_MAP = {"견과류": 5, "땅콩": 6, "갑각류": 7, "생선": 8, "밀": 9, "달걀": 10, "유제품": 11, "대두": 12, "참깨": 13}
VEGAN_BASES = {
    "1": ("Vegan",     [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    "2": ("Ovo",       [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    "3": ("Lacto",     [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    "4": ("Lacto-Ovo", [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    "5": ("Pesco",     [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
}

# ==========================================
# 📥 [1~2단계] 사용자 인터랙티브 설문조사
# ==========================================
def get_user_input_and_create_mask():
    print("=" * 60)
    print("      🌟 K-Food 안전 맞춤형 식단 설문조사 시작 🌟      ")
    print("=" * 60)

    user_vector = np.zeros(14, dtype=int)
    chosen_vegan = "None"
    chosen_allergies = []

    print("[1단계] 해당되는 제한 사항을 모두 골라주세요 (복수 선택 가능, 예: 1,2)")
    print("1: 비건(채식주의) 필터 적용")
    print("2: 알러지 필터 적용")
    print("3: 해당 없음 (일반 식단)")
    main_choice = input("입력: ").strip()

    if "1" in main_choice:
        print("\n[2단계-채식] 당신의 채식 단계를 선택해주세요 (번호 입력)")
        print("1: 비건 | 2: 오보 | 3: 락토 | 4: 락토-오보 | 5: 페스코")
        vegan_choice = input("입력: ").strip()
        if vegan_choice in VEGAN_BASES:
            chosen_vegan, base_mask = VEGAN_BASES[vegan_choice]
            user_vector = np.array(base_mask, dtype=int)

    if "2" in main_choice:
        print("\n[2단계-알러지] 기피하는 글로벌 Top 9 알러지 성분을 선택해주세요 (복수 선택 가능, 예: 대두,밀)")
        print("항목: 견과류, 땅콩, 갑각류, 생선, 밀, 달걀, 유제품, 대두, 참깨")
        allergy_input = input("입력: ").strip()

        input_list = [item.strip() for item in allergy_input.replace(",", " ").split() if item.strip()]
        for allergy in input_list:
            if allergy in ALLERGY_MAP:
                user_vector[ALLERGY_MAP[allergy]] = 1
                chosen_allergies.append(allergy)

    # 크로스 매핑 보정 규칙 적용
    if user_vector[7] == 1 or user_vector[8] == 1: user_vector[2] = 1
    if user_vector[10] == 1: user_vector[3] = 1
    if user_vector[11] == 1: user_vector[4] = 1

    print("\n" + "=" * 60)
    print("👤 유저 식단 마스크 프로필 생성 완료")
    print(f" - 최종 생성된 기피 벡터 (U): {list(user_vector)}")
    print("=" * 60 + "\n")
    return user_vector

# ==========================================
# 🧠 [새로운 2-1단계] AI 기반 식재료 추정
# ==========================================
def get_ai_inferred_ingredients(dish_name):
    """
    공공데이터에 없는 요리에 대해 AI에게 일반적인 재료를 추정해달라고 요청합니다.
    """
    INFERENCE_PROMPT_TEMPLATE = f"""
    너는 요리에 대한 깊은 지식을 가진 AI 조수이다.
    다음 음식 '{dish_name}'에 일반적으로 포함되는 주요 재료들을 5개 이내로 콤마로 구분하여 나열해라.
    예시: "돼지고기, 마늘, 양파, 김치, 파"
    """
    try:
        response = gemini_model.generate_content(
            INFERENCE_PROMPT_TEMPLATE,
            generation_config={'temperature': 0.5}
        )
        raw_ingredients_str = response.text.strip()
        # 콤마로 분리된 재료 문자열을 리스트로 변환
        ingredients = [ing.strip() for ing in raw_ingredients_str.split(',') if ing.strip()]
        return ingredients
    except Exception as e:
        print(f"⚠️ AI 재료 추정 중 에러 발생: {e}. Fallback 데이터를 사용합니다.")
        # AI 추정 실패 시 Fallback 데이터 (단순화된 예시)
        fallback_ingredients = {
            "파채": ["파", "고춧가루", "참기름"],
            "삼겹살": ["돼지고기", "소금", "후추"]
        }
        return fallback_ingredients.get(dish_name, [])

# ==========================================
# ⚙️ [2단계] 공공데이터 CSV 연동 (오직 CSV에서만 추출)
# ==========================================
def build_db_map_from_csv(csv_path, target_dishes):
    """
    제공된 전북특별자치도 공공데이터 CSV 파일을 열어
    지정된 음식명(요리명)에 해당하는 실데이터 '재료내용'을 파싱하여 DB_Map을 빌드합니다.
    """
    # CSV 읽기 시도
    try:
        df = pd.read_csv(csv_path, encoding='cp949')
    except:
        df = pd.read_csv(csv_path, encoding='utf-8')

    print(f"DEBUG: DataFrame columns: {df.columns.tolist()}") # Debug line to print columns

    db_map = {}

    for dish in target_dishes:
        # '음식명' 컬럼에서 해당 음식을 검색 (정확히 일치하는 요리명만)
        matched = df[df['음식명'] == dish]

        if not matched.empty:
            # 실데이터의 '재료' 텍스트 추출 (예: "재료: 된장 3큰술, 두부 1/2모, ...")
            raw_text = str(matched.iloc[0]['재료'])

            # 정규식을 이용해 계량 단위(g, 큰술, 모 등) 및 숫자, 특수문자를 지우고 순수 식재료 명사만 추출
            clean_text = re.sub(r'[^가-힣\s,]', '', raw_text)  # 한글, 공백, 쉼표만 남김
            tokens = [t.strip() for t in clean_text.replace("재료", "").replace("주재료", "").replace("부재료", "").replace(",", " ").split()]

            # 불필요한 단어 제거 및 유니크한 재료 명사 리스트화 (최소 2글자 이상)
            ingredients = list(set([tok for tok in tokens if len(tok) >= 2 and tok not in ["큰술", "작은술", "약간", "적당량"]]))
            db_map[dish] = ingredients
        else:
            print(f"⚠️ [공공데이터 경고] CSV 내에 '{dish}' 요리 데이터가 존재하지 않습니다. AI 추정 재료를 사용합니다.")
            # AI에게 재료 추정 요청
            inferred_ingredients = get_ai_inferred_ingredients(dish)
            db_map[dish] = inferred_ingredients

    return db_map

# ==========================================
# 🧠 [3단계] AI 기반 실시간 성분 판별 (Structured Output)
# ==========================================
def get_ai_structured_labels(ingredients_list):
    """
    공공데이터에서 동적으로 뽑아낸 날것의 식재료 목록을 AI에게 주입하여 14차원 벡터 JSON으로 실시간 변환
    """
    PROMPT_TEMPLATE = f"""
    너는 한식 식재료 성분 분석 AI 엔진이다.
    입력된 식재료 리스트의 각 아이템이 아래 정의된 14차원 인덱스(0~13) 중 어느 곳에 포함되는지 판별해라.
    포함되면 1, 포함되지 않으면 0으로 채운 고정 길이 14의 이진 배열을 반환해라.

    [14차원 인덱스 정의]
    0:육류, 1:가공육, 2:어패류, 3:가금류알, 4:유제품,
    5:견과류알러지, 6:땅콩알러지, 7:갑각류알러지, 8:생선알러지,
    9:밀알러지, 10:달걀알러지, 11:유제품알러지, 12:대두알러지, 13:참깨알러지

    출력 형식: 설명이나 코드 블록 없이 오직 순수한 JSON Object 포맷만 반환할 것. 키값은 입력된 식재료 이름이어야 함.

    [입력 식재료 리스트]: {json.dumps(ingredients_list, ensure_ascii=False)}
    """
    try:
        response = gemini_model.generate_content(
            PROMPT_TEMPLATE,
            generation_config={'response_mime_type': 'application/json'}
        )
        return json.loads(response.text)
    except Exception as e:
        # API 오류 혹은 키가 없을 때 작동하는 완벽한 Fallback 맵 (실제 운영 단계에선 AI 결과가 여기에 대체됨)
        mock_map = {
            "두부": [0,0,0,0,0,0,0,0,0,0,0,0,1,0], "된장": [0,0,0,0,0,0,0,0,0,0,0,0,1,0],
            "멸치": [0,0,1,0,0,0,0,0,1,0,0,0,0,0], "돼지고기": [1,0,0,0,0,0,0,0,0,0,0,0,0,0],
            "삼겹살": [1,0,0,0,0,0,0,0,0,0,0,0,0,0], "참기름": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
            "대파": [0,0,0,0,0,0,0,0,0,0,0,0,0,0], "고춧가루": [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            "애호박": [0,0,0,0,0,0,0,0,0,0,0,0,0,0], "바지락": [0,0,1,0,0,0,1,0,0,0,0,0,0,0],
            "파": [0,0,0,0,0,0,0,0,0,0,0,0,0,0], "소금": [0,0,0,0,0,0,0,0,0,0,0,0,0,0], "후추": [0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        }
        return {k: mock_map.get(k, [0]*14) for k in ingredients_list}

# ==========================================
# 🏁 [4단계] 통합 실행 파이프라인
# ==========================================
if __name__ == "__main__":
    camera_dishes = ["두부된장찌개", "파채", "삼겹살","콩나물무침","연근조림"]
    csv_file_path = "전북특별자치도_음식만드는법_20191219..csv"

    # [1~2단계] 유저 설문조사 구동 -> U 마스크 확보
    U = get_user_input_and_create_mask()

    # [2단계] 진짜 공공데이터 CSV에서 재료 동적 추출 (사전 정의 0%) 또는 AI 추정
    print("🔍 [Step 2] 공공데이터 CSV 파일 내 요리 레시피 검색 및 식재료 동적 추출 또는 AI 추정 중...")
    DB_Map = build_db_map_from_csv(csv_file_path, camera_dishes)
    for dish, ings in DB_Map.items():
        print(f"   📂 DB_Map['{dish}'] (공공데이터 실시간 로드 또는 AI 추정 결과) -> {ings}")

    # [3단계] 공공데이터에서 파싱된 모든 식재료 단어 취합 후 AI 실시간 전송
    all_ingredients = set()
    for ings in DB_Map.values():
        all_ingredients.update(ings)

    print("\n🤖 [Step 3] AI에게 추출된 공공데이터 식재료 목록 14차원 분류 실시간 요청...")
    AI_JSON_OUTPUT = get_ai_structured_labels(list(all_ingredients))

    # AI가 반환한 로우 데이터 원본 출력 확인
    print(f"   📊 AI 실시간 파싱 JSON 응답: {json.dumps(AI_JSON_OUTPUT, ensure_ascii=False, indent=2)}")

    # [4단계] 개별 음식 독립 비트 연산 검사 (Bitwise AND / OR)
    print("\n🚀 [Step 4] 밥상 테이블 독립 비트 연산 Safety Check 가동:")
    print("=" * 70)
    for dish in camera_dishes:
        ingredients = DB_Map[dish]

        # 비트 OR(|)로 공공데이터 식재료 벡터 병합 -> 음식 암호판 F_dish 생성
        F_dish = np.zeros(14, dtype=int)
        for ing in ingredients:
            F_dish = F_dish | np.array(AI_JSON_OUTPUT.get(ing, [0]*14), dtype=int)

        # 유저 벡터(U)와 음식 벡터(F_dish) 비트 AND(&) 연산
        result_vector = U & F_dish
        is_unsafe = np.sum(result_vector) > 0

        if is_unsafe:
            conflicts = [LABELS[i] for i, val in enumerate(result_vector) if val == 1]
            print(f"❌ [{dish}] 섭취 불가능 (위험성분 감지됨: {conflicts})")
        else:
            print(f"🟢 [{dish}] Safe (안전한 음식입니다)")
    print("=" * 70)
    safe_dishes = [] # 진짜 연산 결과로만 채워질 클린 푸드 리스트

    for dish in camera_dishes:
        ingredients = DB_Map[dish]
        F_dish = np.zeros(14, dtype=int)
        for ing in ingredients:
            F_dish = F_dish | np.array(AI_JSON_OUTPUT.get(ing, [0]*14), dtype=int)

        result_vector = U & F_dish
        is_unsafe = np.sum(result_vector) > 0

        if is_unsafe:
            conflicts = [LABELS[i] for i, val in enumerate(result_vector) if val == 1]
            print(f"❌ [{dish}] 위험 성분 감지되어 색출됨 -> 제외 사유: {conflicts})")
        else:
            print(f"🟢 [{dish}] 안전성 검증 통과 -> safe_dishes 리스트에 자동 편입")
            safe_dishes.append(dish) # ★하드코딩 없이 실제 연산 결과로 실시간 적재!

    print("-" * 70)
    print(f"🛡️ 최종 필터링 완료된 실시간 안전 음식 목록 (safe_dishes): {safe_dishes}\n")

# ==========================================
# 🔥 [수정된 5단계] AI 기반 실시간 맞춤형 가이드 변형 (Dynamic Guide Generation)
# ==========================================
import json
print("\n✨ [Step 5] 안전 검증을 통과한 음식 기반 실시간 맞춤형 가이드 매칭 및 리라이팅 시작...")

# 1. 기존에 구축해 둔 마스터 가이드 DB(JSON)를 불러옵니다.
try:
    with open("S1_Final_Database.json", "r", encoding="utf-8") as f:
        s1_database = json.load(f)
    print("📂 S1_Final_Database.json 로드 성공!\n")
except FileNotFoundError:
    print("⚠️ S1_Final_Database.json 파일이 없습니다. Fallback 가이드 생성 모드로 전환합니다.")
    s1_database = []

# 2. 실시간 맞춤형 융합 프롬프트 설계
# safe_dishes(안전이 검증되어 현재 식탁에 있는 요리들) 정보와 마스터 DB를 AI에게 전달합니다.
DYNAMIC_GUIDE_PROMPT = f"""
너는 외국인에게 한식 식사 방법을 친절하게 동적으로 안내해 주는 전문 K-Food 셰프 가이드이다.

[현재 식탁 위에 있는 안전한 음식 리스트 (safe_dishes)]
{json.dumps(safe_dishes, ensure_ascii=False)}
※ 중요: 반드시 위 리스트에 존재하는 음식/반찬/소스만을 조합하여 가이드를 재구성해라.
여기에 없는 재료(예: 상추가 없는데 상추를 싸 먹으라고 하거나, 파채가 없는데 파채를 곁들이라는 등)는 가이드 단계에서 완벽히 제외하거나 생략해라.

[마스터 가이드 레퍼런스 데이터 (참고용 정답지)]
{json.dumps(s1_database, ensure_ascii=False, indent=2)}

[미션]
1. 현재 안전하다고 판명된 음식(`safe_dishes`) 중 '주음식(메인디시, 예: 삼겹살)'을 기준으로 식사 가이드를 작성하되, 참고용 정답지의 'guide_steps_ko' 흐름을 따르세요.
2. 단, `safe_dishes`에 포함되지 않은 보조 재료나 반찬이 언급된 Step은 과감히 삭제하거나, 현재 식탁 위에 있는 다른 안전한 재료로 대체하여 문장을 자연스럽게 수정(Rewriting)하세요.
3. 결과는 사용자가 화면에 바로 순서대로 읽을 수 있게 마크다운 순서형 목록(1., 2., 3.) 형태로 깔끔하게 한글로 출력하세요.
"""

try:
    print("🤖 AI가 현재 식탁 위 재료 상황에 맞추어 먹방 가이드를 최적화(리라이팅) 중입니다...")
    response = gemini_model.generate_content(
        DYNAMIC_GUIDE_PROMPT,
        generation_config={'temperature': 0.3} # 일관된 변형을 위해 온도를 낮춤
    )

    print("\n" + "=" * 70)
    print("🍽️ [실시간 맞춤형 K-Food 먹방 가이드]")
    print("=" * 70)
    print(response.text.strip())
    print("=" * 70)

except Exception as e:
    print(f"⚠️ 실시간 가이드 생성 중 오류 발생: {e}")
    print("💡 [Fallback 안내] 시스템 안정성을 위해 기존 마스터 DB 내용을 필터링 없이 노출합니다.")
    # AI 연산 실패 시 예외 처리용 기존 출력 로직 유지
    for dish in safe_dishes:
        print(f"🍽️ [{dish}] 기본 가이드:")
        matching_guides = [item for item in s1_database if item.get('main_food') == dish]
        if matching_guides:
            for step in matching_guides[0].get('guide_steps_ko', []):
                print(f"   - {step}")
        else:
            print("   - (안내: 등록된 조합 가이드가 없습니다.)")
        print("=" * 70)



import json
import numpy as np
from collections import Counter
from sklearn.metrics.pairwise import cosine_similarity
import math
import os
import time

# 코랩 및 터미널 환경 호환 화면 지우기
def clear_screen():
    try:
        from IPython.display import clear_output
        clear_output(wait=True)
    except ImportError:
        os.system('cls' if os.name == 'nt' else 'clear')

# ==========================================
# 1. 평가용 글로벌 음식 베이스라인 (취향 분석용)
# ==========================================
baseline_foods = {
    "맥앤치즈 (Mac & Cheese)": {"taste": [1, 4, 5, 1], "texture": [1, 2, 4, 4, 1]},
    "하리보 젤리 (Gummy Bear)": {"taste": [4, 1, 1, 3], "texture": [1, 5, 2, 1, 1]},
    "나초칩 & 살사 (Nachos)": {"taste": [1, 4, 1, 3], "texture": [5, 1, 1, 2, 1]},
    "페페로니 피자 (Pizza)": {"taste": [2, 5, 4, 2], "texture": [2, 3, 3, 4, 1]}
}
rating_weights = {"1": -1.5, "2": 0.0, "3": 1.0, "4": 2.0}

# ==========================================
# 2. 유저 맞춤형 '찐친' 멘트 사전 (상황별 디테일)
# ==========================================
situation_comments = {
    "스트레스": "스트레스 팍팍 받는 날엔 이거 먹고 땀 한 번 쭉 빼면 극락이지!",
    "야식": "이 시간에 먹어도 후회 없을 완벽한 꿀조합! 내일 붓는 건 내일 생각하자.",
    "해장": "어제 달린 네 쓰린 속을 싹 씻어내려 줄 구세주 같은 조합 대령이요~",
    "다이어트": "다이어트 중에 입 터졌을 때? 이 조합이면 죄책감 덜고 맛있게 먹을 수 있어!",
    "안주": "혼술할 때 이거 하나면 이자카야 부럽지 않은 극강의 안주 완성!",
    "가성비": "지갑 얇은 날에도 배 터지고 맛있게 먹을 수 있는 갓성비 조합이야.",
    "디저트": "단 거 당길 때 이거 먹으면 입 안에서 폭죽 터진다? 무조건 담아!"
}

# ==========================================
# 3. 데이터 전처리 파이프라인 (초강력 과적합 필터링 적용)
# ==========================================
def preprocess_and_load_db(db_filepath='s2_labeled_database.json'):
    if not os.path.exists(db_filepath):
        print(f"❌ 앗, DB 파일({db_filepath})이 없습니다! 데이터 가공을 먼저 완료해주세요.")
        return None, []

    with open(db_filepath, 'r', encoding='utf-8') as f:
        raw_db = json.load(f)

    # 💡 [핵심 수정] "맥주 안주" -> "안주" 로 완벽하게 묶음!
    keyword_mapping = {
        "간편": "가성비", "분식집": "야식", "매콤": "스트레스",
        "아침": "해장", "간식": "디저트", "술안주": "안주", "숙취": "해장", "술 후": "해장",
        "맥주 안주": "안주", "맥주안주": "안주", "혼술": "안주", "홈술": "안주"
    }

    # 🚫 '여름 청량', '조화' 같은 추상적/감성적 쓰레기 데이터까지 완벽 차단!
    blacklist_keywords = [
        "TOP", "BEST", "베스트", "추천", "리뷰", "방법", "끓이기", "만드는법", "가이드",
        "식단", "다이어트 템", "스트레스 해소 음식", "숙취 해소 음식", "위험성", "조언", "팁",
        "PT", "피티", "피토링", "트레이너", "짐민호", "빅브로짐", "헬스장", "다이어트 식품", "다이어트 도시락",
        "먹방", "파티", "레스토랑", "전문점", "타리즈", "중앙해장", "가산디지털단지", "김량장동", "안양동", "원흥역",
        "오사카", "일본", "로손", "세븐일레븐", "사케", "고량주", "위스키", "보드카", "와인", "부산",
        "심리", "불규칙한", "인공지능", "협업", "토이", "장난감", "일기", "알바생",
        "마녀스프", "냄비", "도시락", "당뇨", "혈당", "사망", "주문법", "한국균", "누룩",
        "기회관", "기업", "팀장님", "5009", "촬영", "영양성분", "복희", "베리", "스마트",
        "브라우니 써봤어", "팔아야 돼", "차량 가격",
        "청량", "시원ness", "야심", "간단 식사", "신상", "대학교", "최적화", "MZ세대",
        "꿀조화", "조화", "테이블에서", "퇴근 후", "금요일", "새벽 경기"
    ]

    # ✂️ 이름에서 지저분한 단어 컷
    remove_words_from_name = [
        "편의점", "레시피", "꿀조합", "조합", "해장 컵라면", "해장라면", "간단 식단", "다이어트", "간식", "음료수"
    ]

    # 남은 이름이 너무 일반명사일 때 거르기 위한 최종 방어선
    generic_names = ["음료", "야식", "안주", "식사", "디저트", "아이스크림"]

    clean_db = []
    seen_combinations = set()

    for item in raw_db:
        if 'taste' not in item or 'texture' not in item: continue

        name = item.get("combination_name", "")
        snippet = item.get("original_snippet", "")

        # 블랙리스트에 걸리면 즉시 아웃
        if any(bad_word in name or bad_word in snippet for bad_word in blacklist_keywords):
            continue

        # 수식어 제거
        core_name = name
        for word in remove_words_from_name:
            core_name = core_name.replace(word, "")
        core_name = core_name.strip()

        # 수식어 뗐더니 이름이 1글자 이하거나, 비어있거나, 추상적 일반 명사면 아웃!
        if len(core_name) < 2 or core_name in seen_combinations or core_name in generic_names:
            continue

        seen_combinations.add(core_name)

        for key in item["taste"]:
            if item["taste"][key] == 0: item["taste"][key] = 1
        for key in item["texture"]:
            if item["texture"][key] == 0: item["texture"][key] = 1

        sits = item.get("situations", [])
        if isinstance(sits, str): sits = [sits]

        # 상황 키워드 매핑 적용
        mapped_sits = list(set([keyword_mapping.get(s, s) for s in sits if s not in ["일상", "none", ""]]))

        item["combination_name"] = core_name
        item["situations"] = mapped_sits
        clean_db.append(item)

    all_situations = [sit for item in clean_db for sit in item["situations"]]
    top_situations = [sit for sit, count in Counter(all_situations).most_common(6)]

    return clean_db, top_situations

# ==========================================
# 4. 안전한 입력 로직 (코랩 버그 픽스 유지)
# ==========================================
def get_valid_input(prompt_text, valid_options):
    time.sleep(0.3)
    while True:
        choice = input(prompt_text).strip()
        if choice in valid_options:
            return choice
        print("  ❌ 앗! 목록에 있는 번호를 정확히 입력해줘.\n")
        time.sleep(0.3)

# ==========================================
# 5. 단계별 사용자 프로필 조사
# ==========================================
def get_user_profile_interactive(top_situations):
    clear_screen()
    print("👩‍🍳 [Step 1/3] 현지 찐친 장금이의 맵부심 테스트\n")
    print("Q1. 한국의 매운맛, 어디까지 감당 가능해?")
    print("  1: 진라면 순한맛도 맵다 (Mild - 맵찔이)")
    print("  2: 신라면 정도는 쌉가능 (Medium - 일반인)")
    print("  3: 불닭볶음면 가져와! (Extreme - 맵고수)")
    spicy_level = get_valid_input(">> 번호 선택 (1~3): ", ["1", "2", "3"])
    spicy_limit = 2 if spicy_level == '1' else (3 if spicy_level == '2' else 5)

    clear_screen()
    print("👩‍🍳 [Step 2/3] 오늘의 무드 파악\n")
    print("Q2. 지금 네 상황에 가장 딱 맞는 걸 골라봐!")

    valid_sit_options = []
    for i, sit in enumerate(top_situations):
        print(f"  {i+1}: {sit}")
        valid_sit_options.append(str(i+1))

    pass_num = str(len(top_situations)+1)
    print(f"  {pass_num}: 딱히 없음 (패스)")
    valid_sit_options.append(pass_num)

    sit_choice = get_valid_input(f">> 번호 선택 (1~{pass_num}): ", valid_sit_options)
    chosen_situation = top_situations[int(sit_choice)-1] if sit_choice != pass_num else ""

    clear_screen()
    print("👩‍🍳 [Step 3/3] 왓챠식 정밀 입맛 분석\n")
    print("Q3. 네 입맛을 정확히 알아야 기깔난 걸 주지. 아래 음식들을 평가해봐!")
    print("  [ 1: Bad(불호) / 2: Soso(보통) / 3: Good(호) / 4: Very Good(극호) ]\n")

    user_vectors = []
    for food_name, features in baseline_foods.items():
        rating = get_valid_input(f"  - {food_name} 어때? (1~4): ", ["1", "2", "3", "4"])
        weight = rating_weights[rating]
        food_vector = np.array(features["taste"] + features["texture"])
        user_vectors.append(food_vector * weight)

    user_vector = np.sum(user_vectors, axis=0)
    v_min, v_max = np.min(user_vector), np.max(user_vector)

    if v_max - v_min == 0:
        normalized_user_vector = np.zeros_like(user_vector, dtype=float)
    else:
        normalized_user_vector = (user_vector - v_min) / (v_max - v_min)

    clear_screen()
    print("✨ 네 입맛 분석 완료! 장금이가 최적의 꿀조합을 찾고 있어...\n")
    time.sleep(1.5)
    return spicy_limit, chosen_situation, normalized_user_vector

# ==========================================
# 6. 매칭 알고리즘 및 큐레이션 결과 출력
# ==========================================
def recommend_kfood(food_db, spicy_limit, situation, user_vector):
    candidates = []

    for food in food_db:
        if food.get("spiciness", 1) > spicy_limit: continue

        taste, texture = food["taste"], food["texture"]
        food_vector = np.array([
            taste.get("sweet", 1), taste.get("salty", 1), taste.get("rich", 1), taste.get("sour", 1),
            texture.get("crispy", 1), texture.get("chewy", 1), texture.get("soft", 1), texture.get("thick", 1), texture.get("popping", 1)
        ])

        if np.linalg.norm(user_vector) > 0 and np.linalg.norm(food_vector) > 0:
            sim = cosine_similarity(user_vector.reshape(1, -1), food_vector.reshape(1, -1))[0][0]
        else:
            sim = 0

        db_situations = food.get("situations", [])
        if situation and situation in db_situations:
            sim += 0.5

        candidates.append({
            "name": food.get("combination_name", "비밀의 꿀조합"),
            "score": sim,
            "original": food.get("original_snippet", "말로 다 표현 못 할 극락의 맛!")
        })

    candidates = sorted(candidates, key=lambda x: x["score"], reverse=True)

    clear_screen()
    print("="*75)
    print("🎉 장금이가 편의점 다 털어서 찾아낸 네 맞춤형 꿀조합 TOP 3 🎉")
    print("="*75)

    if not candidates:
        print("\n앗... 네 조건에 딱 맞는 음식이 지금 편의점에 다 털렸나봐 ㅠㅠ 매운맛을 조금 올려볼까?\n")
        return

    if situation:
        custom_comment = situation_comments.get(situation, f"네가 딱 원하던 '{situation}' 맞춤형 조합이야! 무조건 먹어봐.")
        print(f"✨ [오늘의 무드: {situation}] {custom_comment}\n")
    else:
        print(f"✨ [입맛 저격] 상황을 떠나서 네 입맛 데이터가 멱살 잡고 끌고 온 미친 조합이야!\n")

    for i, item in enumerate(candidates[:3]):
        match_rate = math.ceil(min(max(item['score'] * 50 + 50, 0), 99))

        name = item['name']
        if '+' in name:
            ingredients = " ➕ ".join([ing.strip() for ing in name.split('+')])
        else:
            ingredients = name

        print(f"🥇 [{i+1}위] {name}")
        print(f"   🔥 취향 일치율: {match_rate}%")
        print(f"   🛒 장바구니 필수템: {ingredients}")
        print(f"   💡 장금이의 조리법 & 꿀팁:\n      \"{item['original']}\"")
        print("-" * 75)

# ==========================================
# 메인 실행 블록
# ==========================================
def main():
    # 파일 이름을 확인해주세요!
    food_db, top_situations = preprocess_and_load_db('s2_labeled_database.json')

    if food_db:
        spicy_limit, chosen_situation, user_vector = get_user_profile_interactive(top_situations)
        recommend_kfood(food_db, spicy_limit, chosen_situation, user_vector)

if __name__ == "__main__":
    main()



import json
import numpy as np
from collections import Counter
from sklearn.metrics.pairwise import cosine_similarity
import math
import os
import time

# 코랩 및 터미널 환경 호환 화면 지우기
def clear_screen():
    try:
        from IPython.display import clear_output
        clear_output(wait=True)
    except ImportError:
        os.system('cls' if os.name == 'nt' else 'clear')

# ==========================================
# 1. 평가용 글로벌 음식 베이스라인 (취향 분석용)
# ==========================================
baseline_foods = {
    "맥앤치즈 (Mac & Cheese)": {"taste": [1, 4, 5, 1], "texture": [1, 2, 4, 4, 1]},
    "하리보 젤리 (Gummy Bear)": {"taste": [4, 1, 1, 3], "texture": [1, 5, 2, 1, 1]},
    "나초칩 & 살사 (Nachos)": {"taste": [1, 4, 1, 3], "texture": [5, 1, 1, 2, 1]},
    "페페로니 피자 (Pizza)": {"taste": [2, 5, 4, 2], "texture": [2, 3, 3, 4, 1]}
}
rating_weights = {"1": -1.5, "2": 0.0, "3": 1.0, "4": 2.0}

# ==========================================
# 2. 유저 맞춤형 '찐친' 멘트 사전
# ==========================================
situation_comments = {
    "스트레스": "스트레스 팍팍 받는 날엔 이거 먹고 땀 한 번 쭉 빼면 극락이지!",
    "야식": "이 시간에 먹어도 후회 없을 완벽한 꿀조합! 내일 붓는 건 내일 생각하자.",
    "해장": "어제 달린 네 쓰린 속을 싹 씻어내려 줄 구세주 같은 조합 대령이요~",
    "다이어트": "다이어트 중에 입 터졌을 때? 이 조합이면 죄책감 덜고 맛있게 먹을 수 있어!",
    "안주": "혼술할 때 이거 하나면 이자카야 부럽지 않은 극강의 안주 완성!",
    "가성비": "지갑 얇은 날에도 배 터지고 맛있게 먹을 수 있는 갓성비 조합이야.",
    "디저트": "단 거 당길 때 이거 먹으면 입 안에서 폭죽 터진다? 무조건 담아!"
}

# ==========================================
# 💡 [NEW] 저작권 우회용 말투 변환기 (Paraphraser)
# ==========================================
def paraphrase_snippet(text):
    if not text:
        return "이건 진짜 말로 다 표현 못 할 극락의 맛이야!"

    # 1. 존댓말을 장금이(찐친) 반말로 강제 변환하여 원본 텍스트 훼손
    replacements = {
        "습니다": "어!", "입니다": "이야!", "어요": "어~", "아요": "아~",
        "제가": "내가", "저희는": "우리는", "추천합니다": "무조건 먹어봐!",
        "추천드려요": "완전 강추해!", "요.": "어.", "죠.": "지.",
        "된답니다": "돼!", "바랍니다": "해봐!", "세요": "봐"
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    # 2. 문장이 너무 길면 첫 문장 부근에서 잘라내어 2차 저작물화 (노출 최소화)
    sentences = text.split('.')
    if len(sentences) > 2:
        text = sentences[0] + ". " + sentences[1].strip() + "... (이하 생략)"

    return f"이거 진짜 꿀팁인데, {text.strip()}"

# ==========================================
# 3. 데이터 전처리 파이프라인 (초강력 과적합 필터링 적용)
# ==========================================
def preprocess_and_load_db(db_filepath='s2_labeled_database.json'):
    if not os.path.exists(db_filepath):
        print(f"❌ 앗, DB 파일({db_filepath})이 없습니다! 데이터 가공을 먼저 완료해주세요.")
        return None, []

    with open(db_filepath, 'r', encoding='utf-8') as f:
        raw_db = json.load(f)

    keyword_mapping = {
        "간편": "가성비", "분식집": "야식", "매콤": "스트레스",
        "아침": "해장", "간식": "디저트", "술안주": "안주", "숙취": "해장", "술 후": "해장",
        "맥주 안주": "안주", "맥주안주": "안주", "혼술": "안주", "홈술": "안주"
    }

    blacklist_keywords = [
        "TOP", "BEST", "베스트", "추천", "리뷰", "방법", "끓이기", "만드는법", "가이드",
        "식단", "다이어트 템", "스트레스 해소 음식", "숙취 해소 음식", "위험성", "조언", "팁",
        "PT", "피티", "피토링", "트레이너", "짐민호", "빅브로짐", "헬스장", "다이어트 식품", "다이어트 도시락",
        "먹방", "파티", "레스토랑", "전문점", "타리즈", "중앙해장", "가산디지털단지", "김량장동", "안양동", "원흥역",
        "오사카", "일본", "로손", "세븐일레븐", "사케", "고량주", "위스키", "보드카", "와인", "부산",
        "심리", "불규칙한", "인공지능", "협업", "토이", "장난감", "일기", "알바생",
        "마녀스프", "냄비", "도시락", "당뇨", "혈당", "사망", "주문법", "한국균", "누룩",
        "기회관", "기업", "팀장님", "5009", "촬영", "영양성분", "복희", "베리", "스마트",
        "브라우니 써봤어", "팔아야 돼", "차량 가격",
        "청량", "시원ness", "야심", "간단 식사", "신상", "대학교", "최적화", "MZ세대",
        "꿀조화", "조화", "테이블에서", "퇴근 후", "금요일", "새벽 경기"
    ]

    remove_words_from_name = [
        "편의점", "레시피", "꿀조합", "조합", "해장 컵라면", "해장라면", "간단 식단", "다이어트", "간식", "음료수"
    ]

    generic_names = ["음료", "야식", "안주", "식사", "디저트", "아이스크림"]

    clean_db = []
    seen_combinations = set()

    for item in raw_db:
        if 'taste' not in item or 'texture' not in item: continue

        name = item.get("combination_name", "")
        snippet = item.get("original_snippet", "")

        if any(bad_word in name or bad_word in snippet for bad_word in blacklist_keywords):
            continue

        core_name = name
        for word in remove_words_from_name:
            core_name = core_name.replace(word, "")
        core_name = core_name.strip()

        if len(core_name) < 2 or core_name in seen_combinations or core_name in generic_names:
            continue

        seen_combinations.add(core_name)

        for key in item["taste"]:
            if item["taste"][key] == 0: item["taste"][key] = 1
        for key in item["texture"]:
            if item["texture"][key] == 0: item["texture"][key] = 1

        sits = item.get("situations", [])
        if isinstance(sits, str): sits = [sits]

        mapped_sits = list(set([keyword_mapping.get(s, s) for s in sits if s not in ["일상", "none", ""]]))

        item["combination_name"] = core_name
        item["situations"] = mapped_sits
        clean_db.append(item)

    all_situations = [sit for item in clean_db for sit in item["situations"]]
    top_situations = [sit for sit, count in Counter(all_situations).most_common(6)]

    return clean_db, top_situations

# ==========================================
# 4. 안전한 입력 로직
# ==========================================
def get_valid_input(prompt_text, valid_options):
    time.sleep(0.3)
    while True:
        choice = input(prompt_text).strip()
        if choice in valid_options:
            return choice
        print("  ❌ 앗! 목록에 있는 번호를 정확히 입력해줘.\n")
        time.sleep(0.3)

# ==========================================
# 5. 단계별 사용자 프로필 조사
# ==========================================
def get_user_profile_interactive(top_situations):
    clear_screen()
    print("👩‍🍳 [Step 1/3] 현지 찐친 장금이의 맵부심 테스트\n")
    print("Q1. 한국의 매운맛, 어디까지 감당 가능해?")
    print("  1: 진라면 순한맛도 맵다 (Mild - 맵찔이)")
    print("  2: 신라면 정도는 쌉가능 (Medium - 일반인)")
    print("  3: 불닭볶음면 가져와! (Extreme - 맵고수)")
    spicy_level = get_valid_input(">> 번호 선택 (1~3): ", ["1", "2", "3"])
    spicy_limit = 2 if spicy_level == '1' else (3 if spicy_level == '2' else 5)

    clear_screen()
    print("👩‍🍳 [Step 2/3] 오늘의 무드 파악\n")
    print("Q2. 지금 네 상황에 가장 딱 맞는 걸 골라봐!")

    valid_sit_options = []
    for i, sit in enumerate(top_situations):
        print(f"  {i+1}: {sit}")
        valid_sit_options.append(str(i+1))

    pass_num = str(len(top_situations)+1)
    print(f"  {pass_num}: 딱히 없음 (패스)")
    valid_sit_options.append(pass_num)

    sit_choice = get_valid_input(f">> 번호 선택 (1~{pass_num}): ", valid_sit_options)
    chosen_situation = top_situations[int(sit_choice)-1] if sit_choice != pass_num else ""

    clear_screen()
    print("👩‍🍳 [Step 3/3] 왓챠식 정밀 입맛 분석\n")
    print("Q3. 네 입맛을 정확히 알아야 기깔난 걸 주지. 아래 음식들을 평가해봐!")
    print("  [ 1: Bad(불호) / 2: Soso(보통) / 3: Good(호) / 4: Very Good(극호) ]\n")

    user_vectors = []
    for food_name, features in baseline_foods.items():
        rating = get_valid_input(f"  - {food_name} 어때? (1~4): ", ["1", "2", "3", "4"])
        weight = rating_weights[rating]
        food_vector = np.array(features["taste"] + features["texture"])
        user_vectors.append(food_vector * weight)

    user_vector = np.sum(user_vectors, axis=0)
    v_min, v_max = np.min(user_vector), np.max(user_vector)

    if v_max - v_min == 0:
        normalized_user_vector = np.zeros_like(user_vector, dtype=float)
    else:
        normalized_user_vector = (user_vector - v_min) / (v_max - v_min)

    clear_screen()
    print("✨ 네 입맛 분석 완료! 장금이가 최적의 꿀조합을 찾고 있어...\n")
    time.sleep(1.5)
    return spicy_limit, chosen_situation, normalized_user_vector

# ==========================================
# 6. 매칭 알고리즘 및 큐레이션 결과 출력
# ==========================================
def recommend_kfood(food_db, spicy_limit, situation, user_vector):
    candidates = []

    for food in food_db:
        if food.get("spiciness", 1) > spicy_limit: continue

        taste, texture = food["taste"], food["texture"]
        food_vector = np.array([
            taste.get("sweet", 1), taste.get("salty", 1), taste.get("rich", 1), taste.get("sour", 1),
            texture.get("crispy", 1), texture.get("chewy", 1), texture.get("soft", 1), texture.get("thick", 1), texture.get("popping", 1)
        ])

        if np.linalg.norm(user_vector) > 0 and np.linalg.norm(food_vector) > 0:
            sim = cosine_similarity(user_vector.reshape(1, -1), food_vector.reshape(1, -1))[0][0]
        else:
            sim = 0

        db_situations = food.get("situations", [])
        if situation and situation in db_situations:
            sim += 0.5

        # 💡 [NEW] 원본 텍스트를 파라프레이징 함수에 통과시켜서 저장!
        raw_snippet = food.get("original_snippet", "")
        safe_snippet = paraphrase_snippet(raw_snippet)

        candidates.append({
            "name": food.get("combination_name", "비밀의 꿀조합"),
            "score": sim,
            "original": safe_snippet
        })

    candidates = sorted(candidates, key=lambda x: x["score"], reverse=True)

    clear_screen()
    print("="*75)
    print("🎉 장금이가 편의점 다 털어서 찾아낸 네 맞춤형 꿀조합 TOP 3 🎉")
    print("="*75)

    if not candidates:
        print("\n앗... 네 조건에 딱 맞는 음식이 지금 편의점에 다 털렸나봐 ㅠㅠ 매운맛을 조금 올려볼까?\n")
        return

    if situation:
        custom_comment = situation_comments.get(situation, f"네가 딱 원하던 '{situation}' 맞춤형 조합이야! 무조건 먹어봐.")
        print(f"✨ [오늘의 무드: {situation}] {custom_comment}\n")
    else:
        print(f"✨ [입맛 저격] 상황을 떠나서 네 입맛 데이터가 멱살 잡고 끌고 온 미친 조합이야!\n")

    for i, item in enumerate(candidates[:3]):
        match_rate = math.ceil(min(max(item['score'] * 50 + 50, 0), 99))

        name = item['name']
        if '+' in name:
            ingredients = " ➕ ".join([ing.strip() for ing in name.split('+')])
        else:
            ingredients = name

        print(f"🥇 [{i+1}위] {name}")
        print(f"   🔥 취향 일치율: {match_rate}%")
        print(f"   🛒 장바구니 필수템: {ingredients}")
        print(f"   💡 장금이의 조리법 & 꿀팁:\n      \"{item['original']}\"")
        print("-" * 75)

# ==========================================
# 메인 실행 블록
# ==========================================
def main():
    # 파일 이름을 확인해주세요!
    food_db, top_situations = preprocess_and_load_db('s2_labeled_database.json')

    if food_db:
        spicy_limit, chosen_situation, user_vector = get_user_profile_interactive(top_situations)
        recommend_kfood(food_db, spicy_limit, chosen_situation, user_vector)

if __name__ == "__main__":
    main()

"""### Streamlit Application for K-Food Safety Check

Below is the code for a Streamlit application (`streamlit_app.py`) that encapsulates the K-Food safety check and personalized guide generation. You can run this application to interact with your dietary preferences via a web interface.

After running the next cell, a `streamlit_app.py` file will be created. You can then run it using the command provided in the subsequent cell.
"""



# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# import streamlit as st
# import os
# import json
# import re
# import pandas as pd
# import numpy as np
# import google.generativeai as genai
# import google.api_core.client_options as client_options # Import client_options
# 
# # Google Gemini API 클라이언트 초기화
# try:
#     # Read API key using Streamlit's secrets management
#     GEMINI_API_KEY = st.secrets.get('GEMINI_API_KEY')
#     #st.write(f"DEBUG - Attempting to read GEMINI_API_KEY via st.secrets: {'Key found' if GEMINI_API_KEY else 'Key not found'}")
# 
#     if GEMINI_API_KEY:
#         # Explicitly configure client options to avoid Colab kernel dependency issues
#         genai.configure(
#             api_key=GEMINI_API_KEY,
#             client_options=client_options.ClientOptions(api_endpoint='generativelanguage.googleapis.com')
#         )
#         gemini_model = genai.GenerativeModel('gemini-3-flash-preview')
#     else:
#         st.error("GEMINI_API_KEY not found in .streamlit/secrets.toml. Please ensure it's set.")
#         st.stop()
# except Exception as e:
#     st.error(f"Failed to initialize Gemini API: {e}. Please ensure your GEMINI_API_KEY is set and valid in .streamlit/secrets.toml.")
#     st.stop()
# 
# # Placeholder for gemini_model when API is disabled
# class MockGeminiModel:
#     def generate_content(self, prompt, generation_config=None):
#         # Mock response based on the prompt type
#         if "주요 재료들을 5개 이내로 콤마로 구분하여 나열해라." in prompt:
#             dish_name_match = re.search(r"다음 음식 '([^']*)'에", prompt)
#             dish_name = dish_name_match.group(1) if dish_name_match else "default_dish"
#             fallback_ingredients = {
#                 "두부된장찌개": ["두부", "된장", "호박", "파", "멸치"],
#                 "파채": ["파", "고춧가루", "참기름"],
#                 "삼겹살": ["돼지고기", "소금", "후추"],
#                 "콩나물무침": ["콩나물", "대파", "마늘", "참기름"],
#                 "연근조림": ["연근", "간장", "물엿"]
#             }
#             return MockResponse(','.join(fallback_ingredients.get(dish_name, ["재료1", "재료2"])))
# 
#         elif "14차원 인덱스" in prompt:
#             ingredients_list_match = re.search(r"\[입력 식재료 리스트\]: (.*)", prompt)
#             ingredients_list_str = ingredients_list_match.group(1) if ingredients_list_match else "[]"
#             ingredients_list = json.loads(ingredients_list_str)
#             mock_map = {
#                 "두부": [0,0,0,0,0,0,0,0,0,0,0,0,1,0], "된장": [0,0,0,0,0,0,0,0,0,0,0,0,1,0],
#                 "멸치": [0,0,1,0,0,0,0,0,1,0,0,0,0,0], "돼지고기": [1,0,0,0,0,0,0,0,0,0,0,0,0,0],
#                 "삼겹살": [1,0,0,0,0,0,0,0,0,0,0,0,0,0], "참기름": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
#                 "대파": [0,0,0,0,0,0,0,0,0,0,0,0,0,0], "고춧가루": [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
#                 "애호박": [0,0,0,0,0,0,0,0,0,0,0,0,0,0], "바지락": [0,0,1,0,0,0,1,0,0,0,0,0,0,0],
#                 "파": [0,0,0,0,0,0,0,0,0,0,0,0,0,0], "소금": [0,0,0,0,0,0,0,0,0,0,0,0,0,0], "후추": [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
#                 "콩나물": [0,0,0,0,0,0,0,0,0,0,0,0,1,0], "연근": [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
#                 "간장": [0,0,0,0,0,0,0,0,0,1,0,0,1,0], "식초": [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
#                 "깨소금": [0,0,0,0,0,0,0,0,0,0,0,0,0,1], "진간장": [0,0,0,0,0,0,0,0,0,1,0,0,1,0],
#                 "물엿": [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
#                 "쇠고기": [1,0,0,0,0,0,0,0,0,0,0,0,0,0], "다진": [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
#                 "앙념": [0,0,0,0,0,0,0,0,0,0,0,0,0,0]
#             }
#             return MockResponse(json.dumps({k: mock_map.get(k, [0]*14) for k in ingredients_list}, ensure_ascii=False))
#         elif "맞춤형 가이드" in prompt:
#             safe_dishes_match = re.search(r"""
# \[현재 식탁 위에 있는 안전한 음식 리스트 \(safe_dishes\)\]
# (.*)
# \n\[마스터 가이드 레퍼런스 데이터 \(참고용 정답지\)\]""", prompt, re.DOTALL)
#             safe_dishes_str = safe_dishes_match.group(1) if safe_dishes_match else "[]"
#             safe_dishes = json.loads(safe_dishes_str)
# 
#             if "삼겹살" in safe_dishes:
#                 guide = "1. 잘 구워진 삼겹살 한 점을 집어 드세요.\n2. 구운 마늘과 함께 곁들여 먹으면 더욱 맛있습니다.\n3. 쌈장에 살짝 찍어 드세요."
#             elif "두부된장찌개" in safe_dishes:
#                 guide = "1. 따끈한 두부된장찌개를 밥과 함께 떠 드세요.\n2. 두부와 국물을 함께 맛보며 든든함을 느껴보세요."
#             else:
#                 guide = "1. 준비된 음식을 맛있게 드세요.\n2. 다양한 반찬을 곁들여 풍성하게 즐겨보세요."
#             return MockResponse(guide)
# 
#         return MockResponse("API disabled. Mock response.")
# 
# class MockResponse:
#     def __init__(self, text_content, mime_type='text/plain'):
#         self.text = text_content
#         self.response_mime_type = mime_type
# 
# gemini_model_mock = MockGeminiModel()
# 
# LABELS = [
#     "육류", "가공육", "어패류", "가금류알", "유제품",
#     "견과류", "땅콩", "갑각류", "생선", "밀", "달걀", "유제품알러지", "대두", "참깨"
# ]
# ALLERGY_MAP = {"견과류": 5, "땅콩": 6, "갑각류": 7, "생선": 8, "밀": 9, "달걀": 10, "유제품": 11, "대두": 12, "참깨": 13}
# VEGAN_BASES = {
#     "1": ("Vegan",     [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
#     "2": ("Ovo",       [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
#     "3": ("Lacto",     [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
#     "4": ("Lacto-Ovo", [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
#     "5": ("Pesco",     [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
# }
# 
# def get_ai_inferred_ingredients(dish_name):
#     INFERENCE_PROMPT_TEMPLATE = f"""
#     너는 요리에 대한 깊은 지식을 가진 AI 조수이다.
#     다음 음식 '{dish_name}'에 일반적으로 포함되는 주요 재료들을 5개 이내로 콤마로 구분하여 나열해라.
#     예시: "돼지고기, 마늘, 양파, 김치, 파"
#     """
#     try:
#         response = gemini_model.generate_content(
#             INFERENCE_PROMPT_TEMPLATE,
#             generation_config={'temperature': 0.5}
#         )
#         raw_ingredients_str = response.text.strip()
#         ingredients = [ing.strip() for ing in raw_ingredients_str.split(',') if ing.strip()]
#         return ingredients
#     except Exception as e:
#         st.warning(f"⚠️ AI 재료 추정 중 에러 발생: {e}. Fallback 데이터를 사용합니다.")
#         fallback_ingredients = {
#             "두부된장찌개": ["두부", "된장", "호박", "파", "멸치"],
#             "파채": ["파", "고춧가루", "참기름"],
#             "삼겹살": ["돼지고기", "소금", "후추"],
#             "콩나물무침": ["콩나물", "대파", "마늘", "참기름"],
#             "연근조림": ["연근", "간장", "물엿"]
#         }
#         return fallback_ingredients.get(dish_name, [])
# 
# def build_db_map_from_csv(csv_path, target_dishes):
#     try:
#         df = pd.read_csv(csv_path, encoding='cp949')
#     except Exception:
#         try:
#             df = pd.read_csv(csv_path, encoding='utf-8')
#         except Exception as e:
#             st.error(f"Error reading CSV file at {csv_path}: {e}. Make sure the file exists in the same directory.")
#             return {}
# 
#     db_map = {}
# 
#     for dish in target_dishes:
#         matched = df[df['음식명'] == dish]
# 
#         if not matched.empty:
#             raw_text = str(matched.iloc[0]['재료'])
#             clean_text = re.sub(r'[^가-힣\s,]', '', raw_text)
#             tokens = [t.strip() for t in clean_text.replace("재료", "").replace("주재료", "").replace("부재료", "").replace(",", " ").split()]
#             ingredients = list(set([tok for tok in tokens if len(tok) >= 2 and tok not in ["큰술", "작은술", "약간", "적당량"]]))
#             db_map[dish] = ingredients
#         else:
#             st.info(f"⚠️ [공공데이터 경고] CSV 내에 '{dish}' 요리 데이터가 존재하지 않습니다. AI 추정 재료를 사용합니다.")
#             inferred_ingredients = get_ai_inferred_ingredients(dish)
#             db_map[dish] = inferred_ingredients
#     return db_map
# 
# def get_ai_structured_labels(ingredients_list):
#     PROMPT_TEMPLATE = f"""
#     너는 한식 식재료 성분 분석 AI 엔진이다.
#     입력된 식재료 리스트의 각 아이템이 아래 정의된 14차원 인덱스(0~13) 중 어느 곳에 포함되는지 판별해라.
#     포함되면 1, 포함되지 않으면 0으로 채운 고정 길이 14의 이진 배열을 반환해라.
# 
#     [14차원 인덱스 정의]
#     0:육류, 1:가공육, 2:어패류, 3:가금류알, 4:유제품,
#     5:견과류알러지, 6:땅콩알러지, 7:갑각류알러지, 8:생선알러지,
#     9:밀알러지, 10:달걀알러지, 11:유제품알러지, 12:대두알러지, 13:참깨알러지
# 
#     출력 형식: 설명이나 코드 블록 없이 오직 순수한 JSON Object 포맷만 반환할 것. 키값은 입력된 식재료 이름이어야 함.
# 
#     [입력 식재료 리스트]: {json.dumps(ingredients_list, ensure_ascii=False)}
#     """
#     try:
#         response = gemini_model.generate_content(
#             PROMPT_TEMPLATE,
#             generation_config={'response_mime_type': 'application/json'}
#         )
#         return json.loads(response.text)
#     except Exception as e:
#         st.error(f"⚠️ AI 성분 판별 중 에러 발생: {e}. Fallback 데이터를 사용합니다.")
#         mock_map = {
#             "두부": [0,0,0,0,0,0,0,0,0,0,0,0,1,0], "된장": [0,0,0,0,0,0,0,0,0,0,0,0,1,0],
#             "멸치": [0,0,1,0,0,0,0,0,1,0,0,0,0,0], "돼지고기": [1,0,0,0,0,0,0,0,0,0,0,0,0,0],
#             "삼겹살": [1,0,0,0,0,0,0,0,0,0,0,0,0,0], "참기름": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
#             "대파": [0,0,0,0,0,0,0,0,0,0,0,0,0,0], "고춧가루": [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
#             "애호박": [0,0,0,0,0,0,0,0,0,0,0,0,0,0], "바지락": [0,0,1,0,0,0,1,0,0,0,0,0,0,0],
#             "파": [0,0,0,0,0,0,0,0,0,0,0,0,0,0], "소금": [0,0,0,0,0,0,0,0,0,0,0,0,0,0], "후추": [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
#             "콩나물": [0,0,0,0,0,0,0,0,0,0,0,0,1,0], "연근": [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
#             "간장": [0,0,0,0,0,0,0,0,0,1,0,0,1,0], "식초": [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
#             "깨소금": [0,0,0,0,0,0,0,0,0,0,0,0,0,1], "진간장": [0,0,0,0,0,0,0,0,0,1,0,0,1,0],
#             "물엿": [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
#             "쇠고기": [1,0,0,0,0,0,0,0,0,0,0,0,0,0], "다진": [0,0,0,0,0,0,0,0,0,0,0,0,0,0],
#             "앙념": [0,0,0,0,0,0,0,0,0,0,0,0,0,0]
#         }
#         return {k: mock_map.get(k, [0]*14) for k in ingredients_list}
# 
# import os
# 
# os.makedirs(".streamlit", exist_ok=True)
# 
# config_content = """
# [theme]
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F5F7FA"
# textColor = "#1E2229"
# primaryColor = "#3CD070"
# font = "sans serif"
# """
# 
# with open(".streamlit/config.toml", "w", encoding="utf-8") as f:
#     f.write(config_content.strip())
# 
# st.set_page_config(layout="wide")
# st.title("🌟K-Food 안전 맞춤형 식단 가이드")
# st.markdown("당신의 식단 제한 사항에 맞춰 안전한 K-Food 메뉴와 맞춤형 가이드를 제공합니다.")
# 
# st.header("🥗 1. 식단 제한 설정") # Added emoji
# user_vector = np.zeros(14, dtype=int)
# 
# main_choice_options = ["일반 식단", "비건(채식주의) 필터 적용", "알러지 필터 적용", "비건 + 알러지 필터 적용"]
# main_choice = st.selectbox("어떤 제한 사항이 있으신가요?", main_choice_options)
# 
# chosen_vegan = "None"
# chosen_allergies = []
# 
# if "비건" in main_choice:
#     vegan_choice_map = {
#         "비건": "1", "오보": "2", "락토": "3", "락토-오보": "4", "페스코": "5"
#     }
#     selected_vegan_type = st.selectbox("당신의 채식 단계를 선택해주세요:", list(vegan_choice_map.keys()))
#     if selected_vegan_type:
#         vegan_key = vegan_choice_map[selected_vegan_type]
#         chosen_vegan, base_mask = VEGAN_BASES[vegan_key]
#         user_vector = np.array(base_mask, dtype=int)
# 
# if "알러지" in main_choice:
#     available_allergies = list(ALLERGY_MAP.keys())
#     selected_allergies = st.multiselect("기피하는 알러지 성분을 선택해주세요:", available_allergies)
#     for allergy in selected_allergies:
#         if allergy in ALLERGY_MAP:
#             user_vector[ALLERGY_MAP[allergy]] = 1
#             chosen_allergies.append(allergy)
# 
# st.markdown(f"--- \n ✨ **선택된 식단 조건 요약:** \n - **채식 유형:** {'**' + chosen_vegan + '**' if chosen_vegan != 'None' else '없음'} \n - **알러지:** {', '.join(['**' + a + '**' for a in chosen_allergies]) if chosen_allergies else '없음'}") # Enhanced display
# 
# 
# if user_vector[7] == 1 or user_vector[8] == 1: user_vector[2] = 1
# if user_vector[10] == 1: user_vector[3] = 1
# if user_vector[11] == 1: user_vector[4] = 1
# 
# st.markdown("\n") # Add some vertical space
# 
# camera_dishes = ["두부된장찌개", "파채", "삼겹살","콩나물무침","연근조림"]
# csv_file_path = "전북특별자치도_음식만드는법_20191219..csv"
# 
# if st.button("안전한 음식 찾기 및 가이드 생성"):
#     st.header("🔍 2. 음식 안전성 분석 결과") # Added emoji
#     with st.spinner("✨ K-Food 재료 분석 및 성분 검증 중입니다... 잠시만 기다려주세요!"):
#         DB_Map = build_db_map_from_csv(csv_file_path, camera_dishes)
# 
#         all_ingredients = set()
#         for ings in DB_Map.values():
#             all_ingredients.update(ings)
# 
#         AI_JSON_OUTPUT = get_ai_structured_labels(list(all_ingredients))
# 
#     safe_dishes = []
#     st.subheader("개별 음식 안전성 검사:")
#     for dish in camera_dishes:
#         ingredients = DB_Map.get(dish, [])
#         F_dish = np.zeros(14, dtype=int)
#         for ing in ingredients:
#             F_dish = F_dish | np.array(AI_JSON_OUTPUT.get(ing, [0]*14), dtype=int)
# 
#         result_vector = user_vector & F_dish
#         is_unsafe = np.sum(result_vector) > 0
# 
#         if is_unsafe:
#             conflicts = [LABELS[i] for i, val in enumerate(result_vector) if val == 1]
#             st.error(f"❌ **[{dish}]** 섭취 불가능 (위험성분 감지됨: {', '.join(conflicts)})")
#         else:
#             st.success(f"🟢 **[{dish}]** 안전 (안전성 검증 통과)")
#             safe_dishes.append(dish)
# 
#     st.markdown("---")
#     if safe_dishes:
#         st.subheader("🎉 **최종 안전 음식 목록:**") # Added emoji and bold
#         for dish in safe_dishes:
#             st.write(f"- **{dish}**") # Bold dish names
#     else:
#         st.warning("⚠️ 선택하신 조건에 맞는 안전한 음식을 찾을 수 없습니다.")
# 
#     st.header("🍽️ 3. 맞춤형 K-Food 먹방 가이드") # Added emoji
#     if safe_dishes:
#         with st.spinner("📝 AI 셰프가 당신만을 위한 맞춤 가이드를 작성 중입니다..."):
#             try:
#                 with open("S1_Final_Database.json", "r", encoding="utf-8") as f:
#                     s1_database = json.load(f)
#             except FileNotFoundError:
#                 st.warning("⚠️ S1_Final_Database.json 파일이 없습니다. Fallback 가이드 생성 모드로 전환합니다.")
#                 s1_database = []
# 
#             DYNAMIC_GUIDE_PROMPT = f"""
#             너는 외국인에게 한식 식사 방법을 친절하게 동적으로 안내해 주는 전문 K-Food 셰프 가이드이다.
# 
#             [현재 식탁 위에 있는 안전한 음식 리스트 \(safe_dishes\)]
#             {json.dumps(safe_dishes, ensure_ascii=False)}
# 
#             [마스터 가이드 레퍼런스 데이터 \(참고용 정답지\)]
#             {json.dumps(s1_database, ensure_ascii=False, indent=2)}
# 
#             [미션]
#             1. **가장 중요한 규칙: 가이드에 언급되는 모든 음식, 반찬, 소스는 반드시 `safe_dishes` 리스트에 포함된 것만을 사용해야 합니다. `safe_dishes`에 없는 것은 어떤 이유로든 가이드에 포함할 수 없습니다.**
#             2. `safe_dishes` 리스트에서 '주음식(메인디시)' 역할을 할 수 있는 요리를 찾아 가이드의 중심으로 삼으세요. 만약 `safe_dishes`에 주음식이 없다면, `safe_dishes` 내의 모든 음식을 '반찬'으로 간주하고 반찬 위주의 식사 가이드를 작성하세요.
#             3. `마스터 가이드 레퍼런스 데이터`는 `safe_dishes`에 있는 음식의 가이드 흐름과 구조를 참고하는 용도로만 사용하세요. `safe_dishes`에 없는 음식에 대한 레퍼런스는 완전히 무시하세요.
#             4. `safe_dishes`에 포함되지 않은 보조 재료나 반찬이 `마스터 가이드 레퍼런스 데이터`에서 언급될 경우, 해당 부분을 과감히 삭제하거나, 현재 `safe_dishes`에 있는 다른 안전한 재료로 대체하여 문장을 자연스럽게 수정(Rewriting)하세요.
#             5. 결과는 사용자가 화면에 바로 순서대로 읽을 수 있게 마크다운 순서형 목록(1., 2., 3.) 형태로 깔끔하게 한글로 출력하세요.
#             """
#             try:
#                 response = gemini_model.generate_content(
#                     DYNAMIC_GUIDE_PROMPT,
#                     generation_config={'temperature': 0.3}
#                 )
#                 st.markdown(response.text.strip())
#             except Exception as e:
#                 st.error(f"⚠️ 실시간 가이드 생성 중 오류 발생: {e}")
#                 st.info("💡 [Fallback 안내] 시스템 안정성을 위해 기존 마스터 DB 내용을 필터링 없이 노출합니다.")
#                 for dish in safe_dishes:
#                     st.subheader(f"🍽️ [{dish}] 기본 가이드:")
#                     matching_guides = [item for item in s1_database if item.get('main_food') == dish]
#                     if matching_guides:
#                         for step in matching_guides[0].get('guide_steps_ko', []):
#                             st.write(f"   - {step}")
#                     else:
#                         st.write("   - (안내: 등록된 조합 가이드가 없습니다.)")
#     else:
#         st.info("안전한 음식이 없어 가이드를 생성할 수 없습니다.")

"""### Streamlit 앱에 캐릭터 이미지 추가하기

Streamlit 앱에 이미지를 추가하려면 `st.image()` 함수를 사용하면 됩니다. 로컬 파일 경로 또는 이미지 URL을 제공할 수 있습니다. 예를 들어, `.streamlit/static` 폴더에 `character_image.png`라는 캐릭터 이미지를 저장하고 싶다면 다음과 같이 할 수 있습니다.

먼저, 이미지를 Colab 환경에 업로드하거나 URL을 준비합니다. 그 다음 아래 코드를 `streamlit_app.py` 파일 내에 원하는 위치에 추가합니다.
"""

# 1. pyngrok 설치


# 2. ngrok 설정 및 연결
from pyngrok import ngrok

# 본인의 인증 토큰을 입력하세요
NGROK_AUTH_TOKEN = "3FcV9N0njJxI8SDazvPXq42ZDMf_6bXYLAX3zXtXutQWndWqv"

# ngrok 인증 토큰 설정
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# 3. Streamlit 포트(8501)에 연결
try:
    public_url = ngrok.connect(addr='8501')
    print(f"Streamlit app online at: {public_url}")
    print("Click the link above to view your Streamlit application.")
except Exception as e:
    print(f"Error connecting ngrok: {e}")
    print("Please ensure Streamlit is running on port 8501 (or adjust the port in the code).")



"""이 코드를 `streamlit_app.py`의 적절한 위치(예: `st.set_page_config` 다음에 앱의 상단 또는 사이드바에) 붙여넣고, 이미지 경로를 실제 이미지 파일 또는 URL로 변경하면 됩니다. `width` 매개변수로 이미지 크기를 조절할 수 있습니다."""

import os
from google.colab import userdata

# Ensure the .streamlit directory exists
os.makedirs(".streamlit", exist_ok=True)

# Get the GEMINI_API_KEY from Colab userdata
GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')

# Write the API key to .streamlit/secrets.toml
secrets_content = f"""
GEMINI_API_KEY="{GEMINI_API_KEY}"
"""

with open(".streamlit/secrets.toml", "w") as f:
    f.write(secrets_content.strip())

print("Created .streamlit/secrets.toml with GEMINI_API_KEY.")

import subprocess
import os
import sys
from google.colab import userdata

# 1. API 키 설정
try:
    GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')
    os.environ['GEMINI_API_KEY'] = GEMINI_API_KEY
except:
    print("Warning: GEMINI_API_KEY를 찾을 수 없습니다.")

# 2. 확실한 실행 경로 확보
# 현재 사용 중인 파이썬 실행 파일 경로를 사용하여 streamlit을 찾습니다.
python_path = sys.executable
streamlit_run_path = os.path.join(os.path.dirname(python_path), 'streamlit')

# 3. Streamlit 실행
# subprocess로 직접 실행
streamlit_process = subprocess.Popen(
    [python_path, '-m', 'streamlit', 'run', 'streamlit_app.py', '--server.port', '8501'],
    env=os.environ
)

print("Streamlit app is starting in the background...")

# Install pyngrok


# Set your ngrok authentication token (replace 'YOUR_NGROK_AUTH_TOKEN' with your actual token)
# Get your token from https://dashboard.ngrok.com/auth/your-authtoken
from pyngrok import ngrok
NGROK_AUTH_TOKEN = "3FbIerC7hUIIINqyNVYzwF5ooP4_4q1jnpRju8GssDg5gXcDm" # <-- REPLACE THIS WITH YOUR TOKEN

# Set the ngrok authentication token
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Establish a connection to Streamlit's default port (8501)
# If Streamlit is running on a different port, change this accordingly.
try:
    public_url = ngrok.connect(addr='8501') # Changed 'port' to 'addr'
    print(f"Streamlit app online at: {public_url}")
    print("Click the link above to view your Streamlit application.")
except Exception as e:
    print(f"Error connecting ngrok: {e}")
    print("Please ensure Streamlit is running on port 8501 (or adjust the port in ngrok.connect()).")

"""To run the Streamlit application, execute the following command. You might need to expose the port using `ngrok` or similar tools if running in a cloud environment like Colab and wanting a publicly accessible URL."""

# Install pyngrok


# Set your ngrok authentication token (replace 'YOUR_NGROK_AUTH_TOKEN' with your actual token)
# Get your token from https://dashboard.ngrok.com/auth/your-authtoken
from pyngrok import ngrok
NGROK_AUTH_TOKEN = "3FbIerC7hUIIINqyNVYzwF5ooP4_4q1jnpRju8GssDg5gXcDm" # <-- REPLACE THIS WITH YOUR TOKEN

# Set the ngrok authentication token
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Kill any existing ngrok tunnels to free up resources
ngrok.kill()
print("모든 ngrok 터널이 종료되었습니다.")

# Establish a connection to Streamlit's default port (8501)
# If Streamlit is running on a different port, change this accordingly.
try:
    public_url = ngrok.connect(addr='8501') # Changed 'port' to 'addr'
    print(f"Streamlit app online at: {public_url}")
    print("Click the link above to view your Streamlit application.")
except Exception as e:
    print(f"Error connecting ngrok: {e}")
    print("Please ensure Streamlit is running on port 8501 (or adjust the port in ngrok.connect()).")

from pyngrok import ngrok
ngrok.kill()
print("모든 ngrok 터널이 종료되었습니다.")

from pyngrok import ngrok
import os
import signal

# 1. 모든 ngrok 터널 종료
ngrok.kill()

# 2. 이미 실행 중일지 모르는 streamlit 프로세스 종료


# 백그라운드에서 streamlit 실행
# 실행 후 5초 정도 대기하여 서버가 준비될 시간을 줍니다.
import time
!streamlit run streamlit_app.py &>/dev/null &
time.sleep(5)

from pyngrok import ngrok

# 본인의 토큰 설정 (이미 설정하셨다면 이 줄은 생략 가능합니다)
ngrok.set_auth_token("3FcV9N0njJxI8SDazvPXq42ZDMf_6bXYLAX3zXtXutQWndWqv")

# 터널 연결
public_url = ngrok.connect(addr='8501')
print(f"웹 페이지 접속 주소: {public_url}")


import subprocess
import os
import sys
import time
from google.colab import userdata
from pyngrok import ngrok

# 0. 초기화 (이미 실행 중인 프로세스 종료)

ngrok.kill()

# 1. API 키 설정 (Colab Secrets에 'GEMINI_API_KEY'가 있어야 합니다)
try:
    os.environ['Gemini API Key 2'] = userdata.get('Gemini API Key 2')
except:
    print("주의: GEMINI_API_KEY를 찾을 수 없습니다. Secret 설정을 확인하세요.")

# 2. Streamlit 서버 백그라운드 실행
# 시스템이 'streamlit' 명령어를 못 찾을 때를 대비해 파이썬 모듈(-m)로 실행합니다.
print("Streamlit 서버를 시작합니다...")
streamlit_proc = subprocess.Popen([sys.executable, '-m', 'streamlit', 'run', 'streamlit_app.py', '--server.port', '8501'])
time.sleep(5) # 서버가 완전히 켜질 때까지 5초 대기

# 3. ngrok 연결 (본인의 토큰을 반드시 따옴표 안에 넣으세요!)
print("ngrok 터널을 연결합니다...")
ngrok.set_auth_token("3FcV9N0njJxI8SDazvPXq42ZDMf_6bXYLAX3zXtXutQWndWqv")
public_url = ngrok.connect(addr='8501')

print(f"====================================================")
print(f"웹 페이지 접속 주소: {public_url}")
print(f"====================================================")
